# Generated by Django 3.2.1 on 2021-05-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='price',
            field=models.PositiveIntegerField(null='True'),
            preserve_default='True',
        ),
    ]
