# Generated by Django 3.2.1 on 2021-05-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.auction_listings'),
            preserve_default='True',
        ),
    ]
