# Generated by Django 3.2.1 on 2021-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comments_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='initial_price',
            field=models.PositiveIntegerField(null='True'),
            preserve_default='True',
        ),
    ]
