# Generated by Django 3.2.1 on 2021-05-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listings_initial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='description',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.auction_listings'),
        ),
    ]
