# Generated by Django 3.2.1 on 2021-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210515_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='description',
            field=models.CharField(max_length=200, null='True'),
        ),
    ]
