# Generated by Django 3.2.1 on 2021-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='condition',
            field=models.BooleanField(default=True),
        ),
    ]
