# Generated by Django 3.2.1 on 2021-05-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_listings_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listings',
            old_name='condition',
            new_name='active',
        ),
    ]
